---
- name: Deploy Nginx with Hello, World!
  hosts: ngnix-hosts
  become: true

  tasks:

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Create directory to website
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Create file html with hello World
      ansible.builtin.copy:
        content: Hello World!
        dest: /var/www/html/index.html
        mode: '0755'

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
